### ISSUE TITLE
Make it as package

### ISSUE THREAD

**Issue by Kim-Linhb** [PAXTechnologyInc/POSLink-UI#11]
Publish lib-ui-constant, lib-ui-core as package.

**Comment by anibalbastiass** [comment]
Yes, please. May you publish as Github Packages, please?

**Comment by Kim-Linhb** [comment]
@anibalbastiass Snapshot packages were published, see [Github Packages](https://github.com/orgs/PAXTechnologyInc/packages?repo_name=POSLink-UI).

**Comment by Kim-Linhb** [comment]
it's closed by 2a27a46304ea2848c5a87b6d3a59f0ac544d0948
