### ISSUE TITLE
What would be the stable branch?

### ISSUE THREAD

**Issue by anibalbastiass** [PAXTechnologyInc/POSLink-UI#19]
Hi there!

I actually working on a migration from POSDK to PosLink-UI. I've tested `develop`, `release`, and `master` branches and anyone doesn't work fine. Every branch starts with blank activity (VersionActivity).

So, I tried changing the start Activity to `EnterAmountActivity` expecting that receiving all events and doesn't work fine either.

Can you help me, please?

**Comment by anibalbastiass** [comment]
@zzlipax Can you help me, please?

**Comment by Jolie-Yanglj** [comment]
Dear anibalbastiass：
   Sorry， Current demo code in  app and ui-demo are just sample codes, All interfaces  of customer UI are in the lib-ui-constant and lib-ui-core, so if you want to know more details of those interfaces, please ask @tangmin427 to get specification document.
   For how to customized the EnterAmountActivity  please reference the same name file in the ui-demo (maybe here missing some intent parameters in EnterAmountActivity, according the  specification to add the required parameters in your application ).

**Comment by tangmin427** [comment]
@anibalbastiass You will need to submit your question through PAX Developer Portal, https://developer.pax.us/, we will have dedicated engineer to support you.

**Comment by anibalbastiass** [comment]
Thank you @Jolie-Yanglj and @tangmin427. I'm going to write you about my concern.
Best regards!
